import Loader from "@/components/Loader";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body
                    style={{
                        display: "flex",
                        justifyContent: "center",
                        alignItems: "center",
                        height: "100vh",
                        margin: 0,
                    }}
                >
                    <ClerkLoading>
                        <Loader />
                    </ClerkLoading>
                    <ClerkLoaded>{children}</ClerkLoaded>
                </body>
            </html>
        </ClerkProvider>
    );
}
